### ISSUE TITLE
Investigating about FrontEnd Tech

### ISSUE THREAD

**Issue by mahyaa** [lunatech-labs/teahub#2]
Investigate about what technology can be use for the frontend and come up with a proposal.

**Comment by leo-bogastry** [comment]
The most recommended FE framework I find is Angular.
I have also seen good recommendations for Ember.
Here's a list of some features / opinions I found on each:
Angular - has no dependencies
          - can be faster than Ember
          - easy to test
          - simple to read
              - longer in the market  
Ember - has a few dependencies
             - force to structure your app
         - provides more giving on how to use the framework

I found a post made by a person that was working with Angular and end up by switching to Ember:
http://blog.yodersolutions.com/why-i-recommend-emberjs-over-angularjs/

I would like to know what other people from the project have experience with. For me both platforms are new.

**Comment by vijaykiran** [comment]
I'd prefer react 🙂

./Vijay

**Comment by pepite** [comment]
Question to really ask yourself: do you really need a JS front end? Is is required functionally? What are the implications and how Will it slow down development? How will it affect the software inner complexity?

**Comment by vijaykiran** [comment]
./Vijay

> On 7 Aug 2016, at 09:51, Nicolas Leroux notifications@github.com wrote:
> 
> Question to really ask yourself: do you really need a JS front end?
> Yes. 
> 
> Is is required functionally?

Yes and there architecture is completely in the team's hands. And one of the goal is to learn new things. 

> What are the implications and how Will it slow down development?

We don't care about the timelines 😌see confluence page for more info on the goals. 

> How will it affect the software inner complexity? 

This is also done as part of the architecture exercise. 

> Sent from my iPhone
>

**Comment by pepite** [comment]
Sent from my iPhone

> On 7 aug. 2016, at 10:05, Vijay Kiran notifications@github.com wrote:
> 
> ./Vijay
> 
> > On 7 Aug 2016, at 09:51, Nicolas Leroux notifications@github.com wrote:
> > 
> > Question to really ask yourself: do you really need a JS front end?
> > Yes. 
> > 
> > Is is required functionally?
> 
> Yes and there architecture is completely in the team's hands. And one of the goal is to learn new things. 

You don't really say why functionally it is required. See you build the architecture according to the requirement and not the opposite. This is important to outline since I saw too many projects historically doing exactly the wrong thing: building the architecture and then fitting the architecture to the requirement. Since this is a new learning exercise as well it needs to be outlined. Having said that you are free to have a fun project of course.

> > What are the implications and how Will it slow down development?
> 
> We don't care about the timelines 😌see confluence page for more info on the goals. 

I do care about deadline. And I do care about working software. I though the project was to be treated as customer project? I will read confluence and comment there then.

> > How will it affect the software inner complexity? 
> 
> This is also done as part of the architecture exercise. 

That's the most important part and we should lean to simplicity every time.

> > Sent from my iPhone
> >

**Comment by vijaykiran** [comment]
@pepite  See the [README](https://github.com/lunatech-labs/teahub/blob/master/README.md)

**Comment by leo-bogastry** [comment]
It was decided that we will start by only using Play templates to have something basic to present and after add some UX improvements with (probably) Bootstrap. I say probably because it was left in the air that we can decide for something different in the meantime if we see value in trying some other framework.

**Comment by mahyaa** [comment]
We are going to use Play font-end in the beginning and later on we will migrate to react. We will use bootstrap as the css library.
