### ISSUE TITLE
Connecting Toggl functionality to the front end.

### ISSUE THREAD

**Issue by mahyaa** [lunatech-labs/teahub#21]
Mahya wrote an action that takes the list of projects from Toggl. This function needs the workspace id of the user. In order to have the work space id we should send another request to Toggl. This id now is shown by xxx in ApiTogglService.
Acceptance criteria:
1- Write a n action to get workspace id from Toggl. User does not need to know about this action.
2- Connect the current action 'togglProjects' to the front end so user can see the list of the projects.

There are documents available from Toggl API that explains all the request and responses to Toggl

**Comment by joceron** [comment]
Update status:

Right now, the controller that handles the connection to GitHub redirects the user to an empty page displaying the JSON with the info. If we just try to redirect to the proper page, but passing this JSON as a parameter to the HTML page, the page doesn't know what the JsObject is.

I suspect we should create a model class to parse the JSON to something the HTML page can understand. Some models were made by Dimitrios a few weeks ago. This needs some investigation.

**Comment by joceron** [comment]
Update status:

I will be gone for 2 weeks. Maria is informed of my progress so far.
In summary, we've created a method that receives the apiToken as a parameter, and returns with a model class called 'Workspace'. Inside that class, we have the workspaceID. The model class needs some cleaning because what we get from toogl is a JSON, and we need to parse it.

**Comment by mahyaa** [comment]
Thank you @joceron  and @mariadroman. Have a nice vacation and keep up the good work ;)
